apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-helm
spec:
  destination:
    namespace: user1-bgd-helm
    server: 'https://kubernetes.default.svc'
  source:
    path: content/modules/ROOT/examples/bgd-helm-chart
    repoURL: 'https://github.com/radudd/openshift-gitops-workshop'
    targetRevision: main
    helm:
      valueFiles:
        - custom_values_1/values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
