apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-app
spec:
  destination:
    namespace: digital-bgd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: content/modules/ROOT/examples/bgd
    repoURL: https://github.com/radudd/openshift-gitops-workshop
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
